### PR TITLE
fix(validation): for dynamically accessed fields

### LINKED ISSUE #1623: Validation triggering not working on dynamically accessed props
# 🐛 Bug Report

image

When using dynamic property accessor with the validate attribute it does not validate onchange and only errors on submit when the rules are invoked manually.   This must be due to the fact the validate tries to use the property name when looking for rules to run.

Repro link https://stackblitz.com/edit/au2-conventions?file=src%2Fmy-app.html

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Aurelia          |
| Language         |
| Browser          |
| Bundler          |
| Operating System |
| NPM/Node/Yarn    |

### PR DESCRIPTION
**Pull request by Sayan751**
# Pull Request

### 🎫 Issues

Closes #1623

### CODE REVIEW

File: packages/validation/src/validator.ts [hunk 1]
```diff
@@ -50,14 +50,19 @@ export interface IValidator {
...
+    let propertyName = instruction.propertyName;
     const propertyTag = instruction.propertyTag;
 
     const rules = instruction.rules ?? validationRulesRegistrar.get(object, instruction.objectTag) ?? [];
     const scope = Scope.create({ [rootObjectSymbol]: object });
 
     if (propertyName !== void 0) {
-      return (await rules.find((r) => r.property.name === propertyName)?.validate(object, propertyTag, scope)) ?? [];
+      let rule = rules.find((r) => r.property.name === propertyName);
+      if (rule == null && typeof propertyName === 'string' && propertyName.startsWith('[') && propertyName.endsWith(']')) {
```
Comment (bigopon) [inline packages/validation/src/validator.ts:61]: does this work with 2 level keyed access?

**Review by bigopon — APPROVED** [review]
nice work @Sayan751

File: packages/validation/src/validator.ts (hunk 1 above)
Comment (Sayan751) [reply packages/validation/src/validator.ts:61]: @bigopon Great catch! I have fixed that. Thanks!

File: packages/__tests__/src/validation-html/validate-binding-behavior.spec.ts [hunk 2]
```diff
@@ -1758,20 +1763,21 @@ describe('validation-html/validate-binding-behavior.spec.ts', function () {
...
       // round #3
       component.person.name = 'foo';
       component.person.age = 18;
+      component.person.address = { pin: 123, city: 'foo', line1: 'foo' };
       await domQueue.yield();
 
       validationResult = await validationController.validate();
       assert.strictEqual(validationResult.valid, true, 'validationResult.valid 3');
       assert.deepStrictEqual(
         validationResult.results.map(x => [x.propertyName, x.valid, x.message]),
```
Comment (bigopon) [inline packages/__tests__/src/validation-html/validate-binding-behavior.spec.ts:1779]: it's a bit confusing when we don't have the original form of the expression, since keyed is quite different with member access. Just a note in case we want to add a display name in the future.

**Review by bigopon — APPROVED** [review]
👍 nice fix.
