### PR TITLE
fix: au-slot scoping issue

### LINKED ISSUE #1113: view-model.ref leaks from the custom element boundary
# 🐛 Bug Report
Consider the following parent element
```html
<template>
  <au-slotted-element>
    <child view-model.ref="child"></child>
  </au-slotted-element>
</template>
```
and the following usage
```html
<parent>Parent 1</parent>
<parent>Parent 2</parent>
```

## 🤔 Expected Behavior

`view-model.ref` should grab the correct value

## 😯 Current Behavior

The first parent's view model will have an incorrect child reference, pointing to the second parent's child.

## 🔦 Context

MDC text fields have quite complex hierarchy with slotted elements and floating labels residing in these elements.

## 💻 Code Sample

https://gist.dumber.app/?gist=727aed61d5d505773d9d82f33d8fb631

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Aurelia          | 0.10.0-dev.202102110248
| Language         | Typescript
| Browser          | Chrome
| Bundler          | Webpack
| Operating System | Windows 10
| NPM/Node   | 7/15

### PR DESCRIPTION
**Pull request by Sayan751**
# Pull Request

## 📖 Description

Closes #1113

### CODE REVIEW

File: packages/runtime-html/src/resources/custom-elements/au-slot.ts [hunk 1]
```diff
@@ -50,6 +44,14 @@ export class ProjectionProvider {
   public getProjectionFor(instruction: IInstruction): RegisteredProjections | null {
     return projectionMap.get(instruction) ?? null;
   }
+
+  public registerScopeForAuSlot(auSlotInstruction: IInstruction, scope: Scope): void {
```
Comment (bigopon) [inline packages/runtime-html/src/resources/custom-elements/au-slot.ts:48]: I think we can at least remove `auSlot` out of the naming. It's also unclear what kind of resource auSlot means between element and attribute. For the idea itself, I think this is good, everything should go by instruction 👍

**Review by bigopon — COMMENTED** [review]
I haven't been able to review & test this extensively yet, though I noticed that we are missing some failing test. Can we add the failing test I've prepared here https://github.com/aurelia/aurelia/issues/1167#issuecomment-846356537

File: packages/runtime-html/src/templating/render-context.ts [hunk 2]
```diff
@@ -423,6 +425,8 @@ export class RenderContext implements IComponentFactory {
         name = this.definition.name;
       }
       factory = this.factory = new ViewFactory(name, this, contentType, projectionScope);
+    } else {
+      factory.projectionScope = projectionScope!;
```
Comment (bigopon) [inline packages/runtime-html/src/templating/render-context.ts:429]: At the moment, 2nd and onward occurrence of an element will get the same render context, because of the cached definition. Will this change cause a inverted version of the issue we are fixing, where the 2nd and after occurrence keeps overriding the factory from the previous one.

**Comment by Sayan751** [comment]
> I haven't been able to review & test this extensively yet, though I noticed that we are missing some failing test. Can we add the failing test I've prepared here [#1167 (comment)](https://github.com/aurelia/aurelia/issues/1167#issuecomment-846356537)

I was actually looking for this issue. But somehow it slipped. Thanks for pointing this out. We might be able to close both, if the test passes.

**Comment by AureliaEffect** [comment]
The benchmarking comparison can be found here: https://au2-bench-viewer.azurewebsites.net/compare?branch=master&commit=3e45eadfd2e6d90390c29e10ca14fa5d2771f2c5&branch=topic/1113-au-slot-issue&commit=255b1785e259788eb1a1f5ef7643d8c71888f4af

File: packages/runtime-html/src/templating/render-context.ts (hunk 2 above)
Comment (Sayan751) [reply packages/runtime-html/src/templating/render-context.ts:429]: I don't think so. The `CustomElementRenderer` passes the correct scope to it. For a complied definition, we are registering the projection scope as done here: 
https://github.com/aurelia/aurelia/pull/1173/files#diff-748a8a74b12b942c71bdb1e88059c33be782e1cd8ad1268e1bee625907a0e3e3R374-R377

So I think it won't pick up the old scope.

File: packages/runtime-html/src/resources/custom-elements/au-slot.ts (hunk 1 above)
Comment (Sayan751) [reply packages/runtime-html/src/resources/custom-elements/au-slot.ts]: Done

**Comment by Sayan751** [comment]
@bigopon Added new tests.

**Comment by AureliaEffect** [comment]
The benchmarking comparison can be found here: https://au2-bench-viewer.azurewebsites.net/compare?branch=master&commit=3e45eadfd2e6d90390c29e10ca14fa5d2771f2c5&branch=topic/1113-au-slot-issue&commit=e02418463c4cf5329b22cb84876cfce0b3f4a8e8

File: packages/runtime-html/src/templating/render-context.ts (hunk 2 above)
Comment (bigopon) [reply packages/runtime-html/src/templating/render-context.ts:429]: I checked this out and tested locally by adding the following line
```ts
console.log('assigning projection scope. Has existing:', !!factory.projectionScope);
```
before this line.
Here's what I got for the test at line 1346 (parent/tab-bar/tab)
```
(0LOG: 'assigning projection scope. Has existing:', true
(0LOG: 'assigning projection scope. Has existing:', false
```
Does the overriding of existing scope matter?

File: packages/runtime-html/src/templating/render-context.ts [hunk 3]
```diff
@@ -442,6 +446,27 @@ export class RenderContext implements IComponentFactory {
...
+        if (slotInfo !== null) {
+          if (slotInfo.type === AuSlotContentType.Projection) {
+            projectionProvider.registerScopeFor(instruction, scope);
+          }
+          instructions.push(...(slotInfo.content.instructions?.flat() ?? []));
+        }
+      } else if (instruction instanceof HydrateTemplateController) {
+        instructions.push(...((instruction.def.instructions?.flat() ?? []) as IInstruction[]));
+      }
+    }
```
Comment (bigopon) [inline packages/runtime-html/src/templating/render-context.ts:467]:
```suggestion
    let i = 0;
    while (i < instructions.length) {
      const instruction = instructions[i];
      if (instruction instanceof HydrateElementInstruction) {
        const slotInfo = instruction.slotInfo ?? null;
        if (slotInfo !== null) {
          if (slotInfo.type === AuSlotContentType.Projection) {
            projectionProvider.registerScopeFor(instruction, scope);
          }
          instructions.push(...(slotInfo.content.instructions?.flat() ?? []));
        }
      } else if (instruction instanceof HydrateTemplateController) {
        instructions.push(...((instruction.def.instructions?.flat() ?? []) as IInstruction[]));
      }
      ++i;
    }
```

Comment (Sayan751) [reply packages/runtime-html/src/templating/render-context.ts:467]: I am not sure how does it avoid array mutation.

File: packages/runtime-html/src/templating/render-context.ts (hunk 2 above)
Comment (Sayan751) [reply packages/runtime-html/src/templating/render-context.ts:429]: Overriding of the previous scope was the thing that was missing before. Which caused the issues with incorrect scoping. IMO it is essential in order to make things work correctly. Also note that the `projectionScope` property of view factory is only used exclusively in `AuSlot`.

File: packages/runtime-html/src/templating/render-context.ts (hunk 3 above)
Comment (Sayan751) [reply packages/runtime-html/src/templating/render-context.ts:467]: Also I don't see much point keeping the old instructions in the array, even though those are no longer needed.

Comment (bigopon) [reply packages/runtime-html/src/templating/render-context.ts:467]: It's to help us reduce the cost while iterating, since shift() will cost more than an index property access

File: packages/runtime-html/src/templating/render-context.ts (hunk 2 above)
Comment (Sayan751) [reply packages/runtime-html/src/templating/render-context.ts]: Refactored.

File: packages/runtime-html/src/templating/render-context.ts (hunk 3 above)
Comment (Sayan751) [reply packages/runtime-html/src/templating/render-context.ts]: Done

File: packages/runtime-html/src/templating/render-context.ts [hunk 4]
```diff
@@ -442,6 +444,28 @@ export class RenderContext implements IComponentFactory {
...
+    if (targetedProjections === null) { return; }
+    const scope = targetedProjections.scope;
+    const projectionProvider = this.projectionProvider;
+    const instructions = this.compiledDefinition.instructions.flat();
+    let i = 0;
+    while (i < instructions.length) {
+      const instruction = instructions[i++];
+      if (instruction instanceof HydrateElementInstruction) {
+        const slotInfo = instruction.slotInfo ?? null;
+        if (slotInfo !== null) {
```
Comment (bigopon) [inline packages/runtime-html/src/templating/render-context.ts:457]: we should have less code & generated code this way, while perf should be better too.
```suggestion
        const slotInfo = instruction.slotInfo;
        if (slotInfo != null) {
```

File: packages/runtime-html/src/templating/render-context.ts [hunk 5]
```diff
@@ -442,6 +444,28 @@ export class RenderContext implements IComponentFactory {
     return this;
   }
 
+  private $registerScopeForAuSlot(targetedProjections: RegisteredProjections | null): void {
```
Comment (bigopon) [inline packages/runtime-html/src/templating/render-context.ts:447]: This naming is different with the rest of our methods, Is the intention make this method semi private?

File: packages/runtime-html/src/templating/render-context.ts [hunk 6]
```diff
@@ -70,7 +70,7 @@ export interface IRenderContext extends IContainer {
    *
    * @returns Either a new `IViewFactory` (if this is the first call), or a cached one.
    */
-  getViewFactory(name?: string, contentType?: AuSlotContentType, projectionScope?: Scope | null): IViewFactory;
```
Comment (bigopon) [inline packages/runtime-html/src/templating/render-context.ts:73]: I like this, immediately looks cleaner and should make the refactoring easier too.

File: packages/runtime-html/src/templating/controller.ts [hunk 7]
```diff
@@ -332,8 +332,6 @@ export class Controller<C extends IViewModel = IViewModel> implements IControlle
     const { projectionsMap, shadowOptions, isStrictBinding, hasSlots, containerless } = compiledContext.compiledDefinition;
```
Comment (bigopon) [inline packages/runtime-html/src/templating/controller.ts:332]: probably should delete `projectionMap` from the compiled definition too?

**Review by bigopon — COMMENTED** [review]
Both the fixes seem good, though this fix looks a lot nicer than the previous. Nice one.

**Comment by AureliaEffect** [comment]
The benchmarking comparison can be found here: https://au2-bench-viewer.azurewebsites.net/compare?branch=master&commit=3e45eadfd2e6d90390c29e10ca14fa5d2771f2c5&branch=topic/1113-au-slot-issue&commit=9ef966464bd2b05045a7c5e0f893375a4c43e5af

File: packages/runtime-html/src/templating/render-context.ts (hunk 5 above)
Comment (Sayan751) [reply packages/runtime-html/src/templating/render-context.ts]: Renamed.

File: packages/runtime-html/src/templating/controller.ts (hunk 7 above)
Comment (Sayan751) [reply packages/runtime-html/src/templating/controller.ts:332]: Nope. That should be there.

**Comment by AureliaEffect** [comment]
The benchmarking comparison can be found here: https://au2-bench-viewer.azurewebsites.net/compare?branch=master&commit=3e45eadfd2e6d90390c29e10ca14fa5d2771f2c5&branch=topic/1113-au-slot-issue&commit=ded736d8235dca912b642dc50f90cdde1314645f
