### PR TITLE
fix(router-lite): element injection for routed view-model

### LINKED ISSUE #2009: Host element Injection bug?
I noticed something, not sure if it's a bug or not.

When injecting a components/routes host into the view model (not sure if this is correct wording)

```
@inject(Element)

class MyComponent {
  constructor(host) {
    this.host = host
  }
}
```

if the host element differs depending on whether it's a component or a route.

For a route the host element is `au-view`

For a component the host element is the component.

e.g

my-route -> host is `<au-view>
my-component -> host is `<my-component>

Should it not also be `<my-route>` for a route.

Here is an example: https://stackblitz.com/edit/aurelia-2-host-injection-bug

### PR DESCRIPTION
**Pull request by Sayan751**
# Pull Request

## 📖 Description

This PR fixes the issue where the host for routed view-model in router-lite was not registered for injection.

### 🎫 Issues

Closes #2009.

### CODE REVIEW

File: packages/router-lite/src/route-context.ts [hunk 1]
```diff
@@ -186,6 +190,7 @@ export class RouteContext {
     this._moduleLoader = parentContainer.get(IModuleLoader);
 
     const container = this.container = parentContainer.createChild();
+    this._platform = container.get(IPlatform);
```
Comment (bigopon) [inline packages/router-lite/src/route-context.ts:193]:
```suggestion
    const platform = this._platform = container.get(IPlatform);
```
though it seems we don't use `_platform`?

**Review by bigopon — APPROVED** [review]
Nice work @Sayan751

File: packages/router-lite/src/route-context.ts (hunk 1 above)
Comment (Sayan751) [reply packages/router-lite/src/route-context.ts:193]: We have not used the platform in the ctor but in `_createComponentAgent`.
image

**Comment by Sayan751** [comment]
@bigopon I have merged this one. In case you have any further comments, let me know.
