### PR TITLE
fix(router-lite): recovery from unconfigured route

### LINKED ISSUE #1341: router-lite: Once router error is triggered, the router does not recover
If, for whatever reason an error is triggered in the console, the router is never able to recover. A good example of this is the repository I created is attempting to click the "View Profile" menu item, seeing the console error and then attempting to navigate to the welcome or about page, the router does nothing and no further errors are triggered.

Furthermore, you'll notice more weird behaviour. Go to the "About" tab first, see the about page load and then click "View Profile" an error appears in the console, the URL remains the same `http://localhost:9000/about` however, it appears to have gone back to the default route as we see `Welcome to Aurelia 2!` — what should happen if a route fails is that it falls back to the prior working route (looks like maybe it attempts to do that considering the URL remains the same as the current route).

### PR DESCRIPTION
**Pull request by Sayan751**
# Pull Request

### 🎫 Issues

Closes #1341 by handling the errors triggered due to the encounter of un-configured routes, and enqueuing the previous instruction tree.
Note that due to that current design, re-invocation of some hooks is unavoidable. This can be avoided, if the whole path is recognized eagerly, and cancelling the transition as a whole in a more clean way. However, I am planning to push the eager recognition of the paths to later.

## ⏭ Next Steps

Documentation.

### CODE REVIEW

File: packages/router-lite/src/router.ts [hunk 1]
```diff
@@ -194,7 +194,13 @@ export class NavigationOptions extends RouterOptions {
   }
 }
 
+/** @internal */
+export class UnknownRouteError extends Error { }
+
 export class Transition {
+  private _erredWithUnknownRoute: boolean = false;
```
Comment (bigopon) [inline packages/router-lite/src/router.ts:201]: should be marked internal.

File: packages/router-lite/src/validation.ts [hunk 2]
```diff
@@ -8,7 +8,7 @@ import { tryStringify } from './util';
 /**
  * @returns `true` if the given `value` is an non-null, non-undefined, and non-CustomElement object.
  */
-export function isNotNullishOrTypeOrViewModel(value: RouteableComponent | IChildRouteConfig | null | undefined): value is PartialCustomElementDefinition | IChildRouteConfig {
+function isNotNullishOrTypeOrViewModel(value: RouteableComponent | IChildRouteConfig | null | undefined): value is PartialCustomElementDefinition | IChildRouteConfig {
```
Comment (bigopon) [inline packages/router-lite/src/validation.ts:11]: 👍

File: packages/router-lite/src/viewport-agent.ts [hunk 3]
```diff
@@ -48,6 +48,7 @@ export class ViewportAgent {
 
   private currTransition: Transition | null = null;
   private prevTransition: Transition | null = null;
+  private _cancellationPromise: Promise<void> | void | null = null;
```
Comment (bigopon) [inline packages/router-lite/src/viewport-agent.ts:51]: should be marked internal

File: packages/router-lite/src/viewport-agent.ts [hunk 4]
```diff
@@ -180,43 +181,45 @@ export class ViewportAgent {
...
-            case 'invoke-lifecycles':
-            case 'replace':
-              this.currState = State.currCanUnload;
-              b1.push();
-              Batch.start(b2 => {
-                this.logger.trace(`canUnload() - finished invoking on children, now invoking on own component at %s`, this);
-                this.curCA!.canUnload(tr, this.nextNode, b2);
-              }).continueWith(() => {
-                this.logger.trace(`canUnload() - finished at %s`, this);
+    void onResolve(this._cancellationPromise, () => {
```
Comment (bigopon) [inline packages/router-lite/src/viewport-agent.ts:184]: will it matter if cancellation promise throws? there's no catch here

**Comment by bigopon** [comment]
My comments are non blocking, so I'll go ahead and merge this to prepare for the alpha 41 release. Thanks @Sayan751

File: packages/router-lite/src/viewport-agent.ts (hunk 4 above)
Comment (Sayan751) [reply packages/router-lite/src/viewport-agent.ts:184]: If the cancellation promise throws, then possibly it is because of dev-land error. I think it won't be wise to handle that error, as that should be corrected by devs, in my opinion.

File: packages/router-lite/src/viewport-agent.ts (hunk 3 above)
Comment (Sayan751) [reply packages/router-lite/src/viewport-agent.ts:51]: Preparing changes in a different branch. Thanks!

File: packages/router-lite/src/router.ts (hunk 1 above)
Comment (Sayan751) [reply packages/router-lite/src/router.ts:201]: Preparing changes in a different branch. Thanks!

File: docs/engineering-notes/router-architecture-notes.md [hunk 5]
```diff
@@ -111,9 +119,61 @@ This process starts with 3 things:
...
+    - compile the viewport instruction to a routing node, and
+    - append it to the given node
+- ELSE drill down the children of the given node and call [update node](#updating-a-route-node) on the children. The goal is to reach the children until the route context of the child node(s) is matched with the one given.
+
+## Compiling viewport instruction and appending to node
+
+This process starts with a route node and a viewport instruction.
+Quite evidently, in this step the viewport instruction is compiled to a route node, and later down the line the new route node is added as a children to the given route node.
+
+Once the child node is created, the process of **appending** the node is very straight-forward.
```
[the remark this answers is not in the document]
Comment (Sayan751) [reply docs/engineering-notes/router-architecture-notes.md:143]: Preparing changes in a different branch. Thanks! 😄

File: docs/engineering-notes/router-architecture-notes.md [hunk 6]
```diff
@@ -111,9 +119,61 @@ This process starts with 3 things:
...
+    - get the default components for the viewports,
+    - create a view port instruction for the default component,
+    - compile the viewport instruction to a routing node, and
+    - append it to the given node
+- ELSE drill down the children of the given node and call [update node](#updating-a-route-node) on the children. The goal is to reach the children until the route context of the child node(s) is matched with the one given.
+
+## Compiling viewport instruction and appending to node
+
+This process starts with a route node and a viewport instruction.
+Quite evidently, in this step the viewport instruction is compiled to a route node, and later down the line the new route node is added as a children to the given route node.
```
[the remark this answers is not in the document]
Comment (Sayan751) [reply docs/engineering-notes/router-architecture-notes.md:141]: Preparing changes in a different branch. Thanks! 😄

File: docs/engineering-notes/router-architecture-notes.md [hunk 7]
```diff
@@ -111,9 +119,61 @@ This process starts with 3 things:
...
+Depending on the type of the viewport instruction, the route node can be **compiled** differently.
+In this phase the viewport instruction can be categorized broadly into string instruction and routed view-model or custom element definition instruction.
+
+Compiling **from the routed view-model or custom element definition instruction** is relatively easier.
+It involves
+- resolving the route definition
+- generating the viewport instruction using the routing context, from the route definition; [details](#generating-viewport-instruction)
+- creating a configured node from the viewport instruction; the details can be found [here](#creating-configured-route-node).
+
+Compiling **from the sting instruction** is inherently bit more involved.
```
[the remark this answers is not in the document]
Comment (Sayan751) [reply docs/engineering-notes/router-architecture-notes.md:155]: Preparing changes in a different branch. Thanks! 😄
