### PR TITLE
fix(router-lite): specific module import

### LINKED ISSUE #1530: Router lite does not work with lazily imported classes
# 🐛 Bug Report

Currently, router lite recognizes this pattern
```ts
@route({
  routes: [
    { path: '', component: () => import('./pages/home')},
  ],
})
```
but it doesn't work with
```ts
@route({
  routes: [
    { path: '', component: () => import('./pages/home').then((m) => m.Home) },
  ],
})
```
because it assumes the component will be a whole module, instead of a class in that module.

Repro link
https://stackblitz.com/edit/au2-conventions-j5xjkh?file=src%2Fmy-app.ts

## 🤔 Expected Behavior

It should work with any kind of lazily resolved classes:
```ts
Promise.resolve(class {})
import('...').then(m => m.Class)
```

### PR DESCRIPTION
**Pull request by Sayan751**
# Pull Request

### 🎫 Issues

Closes #1530

### CODE REVIEW

**Comment by Sayan751** [comment]
@bigopon I am merging this. In case you see any issue, please let me know.

File: packages/router-lite/src/route-context.ts [hunk 1]
```diff
@@ -439,6 +439,13 @@ export class RouteContext {
 
   public resolveLazy(promise: Promise<IModule>): Promise<CustomElementDefinition> | CustomElementDefinition {
     return this.moduleLoader.load(promise, m => {
```
Comment (bigopon) [inline packages/router-lite/src/route-context.ts:441]: it feels weird we are sending the promise towards module loader regardless. A bit wasteful, inappropriate and side-effect-ful. Shouldn't we do the check here before analyzing the module?

Comment (Sayan751) [reply packages/router-lite/src/route-context.ts:441]: I wouldn't like to create a branching here, to be honest. The module loader is at the end a promise resolver in a way. Also, technically, you can export a module from another module. In terms of promise, that might look something like this:

```ts
Promise.resolve({exportedModule: Promise.resolve({CE})}).then(x => x.exportedModule)
```

In this case, it is expected the `CE` is used as the routed component. I think creating a check here would eventually cause duplicated effort. IMO, it is best to avoid that in favour of supporting broader use cases and non-duplicated code.

Comment (bigopon) [reply packages/router-lite/src/route-context.ts:441]: I see, thanks. I think a small correction for the example would be
```ts
Promise.resolve({exportedModule: {CE} }).then(x => x.exportedModule)
```
since that would be close to how the export statements are transformed into.
